export enum ErrorCodeName {
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  BAD_USER_INPUT = 'BAD_USER_INPUT',
  FORBIDDEN = 'FORBIDDEN',
  NON_DETERMINISTIC_AUTHORIZATION = 'NON_DETERMINISTIC_AUTHORIZATION',
}

export enum ErrorName {
  FORBIDDEN = 'Frobidden',
  UNAUTHORIZED = 'Unauthorized',
  BAD_REQUEST = 'Bad Request',
}
